window.esdocSearchIndex = [
  [
    "github-issues-label-sync~githubissueslabelsync",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html",
    "<span>GithubIssuesLabelSync</span> <span class=\"search-result-import-path\">github-issues-label-sync</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/labelsync.js",
    "file/lib/LabelSync.js.html",
    "lib/LabelSync.js",
    "file"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#constructor",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-constructor-constructor",
    "lib/LabelSync.js~GithubIssuesLabelSync#constructor",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#createlabel",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-createLabel",
    "lib/LabelSync.js~GithubIssuesLabelSync#createLabel",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#createlabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-createLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#createLabels",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#createdlabel",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-createdLabel",
    "lib/LabelSync.js~GithubIssuesLabelSync#createdLabel",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#createdlabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-createdLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#createdLabels",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#deletelabel",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-deleteLabel",
    "lib/LabelSync.js~GithubIssuesLabelSync#deleteLabel",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#deletelabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-deleteLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#deleteLabels",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#deletedlabel",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-deletedLabel",
    "lib/LabelSync.js~GithubIssuesLabelSync#deletedLabel",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#deletedlabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-deletedLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#deletedLabels",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#getlabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-getLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#getLabels",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#github",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-github",
    "lib/LabelSync.js~GithubIssuesLabelSync#github",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#github",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-github",
    "lib/LabelSync.js~GithubIssuesLabelSync#github",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#importlabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-importLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#importLabels",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#labels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-labels",
    "lib/LabelSync.js~GithubIssuesLabelSync#labels",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#labels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-labels",
    "lib/LabelSync.js~GithubIssuesLabelSync#labels",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#options",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-options",
    "lib/LabelSync.js~GithubIssuesLabelSync#options",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#options",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-options",
    "lib/LabelSync.js~GithubIssuesLabelSync#options",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#purgelabels",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-method-purgeLabels",
    "lib/LabelSync.js~GithubIssuesLabelSync#purgeLabels",
    "method"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#repo",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-repo",
    "lib/LabelSync.js~GithubIssuesLabelSync#repo",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#repo",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-repo",
    "lib/LabelSync.js~GithubIssuesLabelSync#repo",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#token",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-token",
    "lib/LabelSync.js~GithubIssuesLabelSync#token",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#token",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-token",
    "lib/LabelSync.js~GithubIssuesLabelSync#token",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#user",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-get-user",
    "lib/LabelSync.js~GithubIssuesLabelSync#user",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync#user",
    "class/lib/LabelSync.js~GithubIssuesLabelSync.html#instance-set-user",
    "lib/LabelSync.js~GithubIssuesLabelSync#user",
    "member"
  ],
  [
    "lib/labelsync.js~githubissueslabelsync.label",
    "typedef/index.html#static-typedef-Label",
    "lib/LabelSync.js~GithubIssuesLabelSync.Label",
    "typedef"
  ]
]